### ISSUE TITLE
Whitespace painting of patterns

### ISSUE THREAD

**Issue by mpapis** [toptal/codeowners-checker#23]
1. Implement option to allow `no_whitespace`, `preserve` and `enforce`
2. Implement detecting whitespace painting
3. Implement the whitespace painting of patterns according to the option

example whitespace painting:
```
/file.rb        @owner
/dir/another.rb @owner
```

**Comment by jonatas** [comment]
We make it preserve the spaces and when we add a file in a group it also considers the previous indent and follows the same ident.
