### ISSUE TITLE
Fix the code / documentation of Array.delete

### ISSUE THREAD

**Issue by ekadlecova** [toptal/codeowners-checker#26]
`Array.delete` has a bug - it uses `==` to compare objects for removal, but the docs state it uses `equal?` - which is not right, we need to open a PR to fix the code / documentation for it.

Solution to this problem we are now using in our code:
https://github.com/toptal/codeowners-checker/blob/20dc8cdd53066228de79bc1ccf90ceae1e91099f/lib/codeowners/checker/array.rb

**Comment by jonatas** [comment]
Already done.
