### ISSUE TITLE
Move `codeowners_filename` to `CodeOwners` class

### ISSUE THREAD

**Issue by mpapis** [toptal/codeowners-checker#31]
https://github.com/toptal/codeowners-checker/blob/2115f48f18ad5b9d05e63d723cab42b4199f029a/lib/codeowners/checker.rb#L117

This method belongs more as a class method in `CodeOwners` class.

**Comment by ryuchan00** [comment]
👀

**Comment by ryuchan00** [comment]
I try it.

**Comment by mmrazik** [comment]
Was done as part of https://github.com/toptal/codeowners-checker/pull/59/files
