### ISSUE TITLE
Validate owners with a file / external API

### ISSUE THREAD

**Issue by mpapis** [toptal/codeowners-checker#39]
There was one instance where owner/team was wrong and it broke the automatic reviewers process on Github, we should be able to validate owners with either a file or when possible external APIs like Github or Gitlab. 

As a first step we could add regexp to validate one of: `@person` `@company/team` `email@example.com`.

**Comment by mmrazik** [comment]
Covered in https://github.com/toptal/codeowners-checker/pull/59
