### ISSUE TITLE
Open source Code Ownership Checker

### ISSUE THREAD

**Issue by ekadlecova** [toptal/codeowners-checker#6]
The https://github.com/toptal/codeowners-checker seems like a great candidate to be open source.

The code is not related to our core and the tool can be useful for other companies that use the same ownership boundaries.

The objective of the task is:

1. Remove all Toptal references in the internal code
2. Write the necessary documentation about how to use the tool
3. Release as open source
4. Announce to the world

**Comment by mpapis** [comment]
done
