### ISSUE TITLE
Missing fetch command

### ISSUE THREAD

**Issue by eskerber** [toptal/codeowners-checker#68]
When running the fetch command via CLI, an error indicates the command does not exist:

```bash
$ codeowners-checker fetch
Could not find command "fetch".
```

I installed via `gem install codeowners-checker`, which may not have updated the gemspec since the change was made (?)

**Comment by jonatas** [comment]
Good point @eskerber ! Looks like we missed releasing a new version after implementing the command. We're very closer to merge #69 and several improvements are being made there. If you want to use it in your local, please make the install procedure manually:


```
git clone ...
cd folder
rake install
```

Use it from master and it should be working. I tested with #69 branch and it worked well.

**Comment by eskerber** [comment]
Thanks! That does work for me!

Feel free to close this if you'd like, else close it when you make your next release.
